name: inspector
description: A Flutter package for inspecting widgets. Useful for quick debugging or QA testing.
version: 2.2.0
homepage: https://github.com/kekland/inspector

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
